services:
  from_others:
    build: .
    tty: true
    stdin_open: true
    command: /bin/bash
    volumes:
      - /data/openreal2sim/tools:/data/openreal2sim/tools
      - /data/openreal2sim/divleen:/data/openreal2sim/divleen
      - /data/openreal2sim/esteban:/data/openreal2sim/esteban
      - /data/openreal2sim/junsoo:/data/openreal2sim/junsoo
      - /data/openreal2sim/peiqi:/data/openreal2sim/peiqi
      - /data/openreal2sim/scene_00020:/data/openreal2sim/scene_00020
      - /data/openreal2sim/peiqi_scene:/data/openreal2sim/peiqi_scene
      - /data/openreal2sim/scripts:/data/openreal2sim/scripts
      - /data/openreal2sim/reconstructions:/data/openreal2sim/reconstructions
    working_dir: /data/openreal2sim
    environment:
      - PYTHONPATH=/data/openreal2sim
